AUTOMAKE_OPTIONS = foreign

#Put here all the ADARI reports
REPORTFILES = gravity_calibrator.py gravity_master_dark.py gravity_p2vm.py gravity_rawdisp.py gravity_util.py gravity_wavelength.py __init__.py

#This installs the reports in reportsdir directory
reports_DATA = $(REPORTFILES)

EXTRA_DIST = $(REPORTFILES)


