/***********************************************************
# "@(#) $Id$" 
#
# Error Include File    Created on  Jul 28 08:05:00 2015
# 
# This file has been generated by a utility
# 
#  !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
# 
***********************************************************/
#ifndef dbERRORS_H
#define dbERRORS_H 

#ifndef CCS_H
#include "ccs.h"
#endif 

#define dbErrOffset 200
 
#ifndef __cplusplus

#define ccsERR_DB_OPEN               ((vltINT16) ( dbErrOffset + 1 ))
#define ccsERR_DB_CLOSE              ((vltINT16) ( dbErrOffset + 2 ))
#define ccsERR_DB_GET_HANDLE         ((vltINT16) ( dbErrOffset + 3 ))
#define ccsERR_DB_INV_LINK           ((vltINT16) ( dbErrOffset + 4 ))
#define ccsERR_DB_INV_ACTION         ((vltINT16) ( dbErrOffset + 5 ))
#define ccsERR_DB_QUERY              ((vltINT16) ( dbErrOffset + 6 ))
#define ccsERR_DB_GETCWP             ((vltINT16) ( dbErrOffset + 7 ))
#define ccsERR_DB_SETCWP             ((vltINT16) ( dbErrOffset + 8 ))
#define ccsERR_DB_GROUP              ((vltINT16) ( dbErrOffset + 9 ))
#define ccsERR_DB_CATEGORY           ((vltINT16) ( dbErrOffset + 10 ))
#define ccsERR_DB_WRITE              ((vltINT16) ( dbErrOffset + 11 ))
#define ccsERR_DB_READ               ((vltINT16) ( dbErrOffset + 12 ))
#define ccsERR_DB_LCU                ((vltINT16) ( dbErrOffset + 13 ))
#define ccsERR_DB_LCU_FORMAT         ((vltINT16) ( dbErrOffset + 14 ))
#define ccsERR_DB_LOCK               ((vltINT16) ( dbErrOffset + 15 ))
#define ccsERR_DB_UNLOCK             ((vltINT16) ( dbErrOffset + 16 ))
#define ccsERR_DB_LCU_REPLY          ((vltINT16) ( dbErrOffset + 17 ))
#define ccsERR_DB_INV_NAME           ((vltINT16) ( dbErrOffset + 20 ))
#define ccsERR_DB_DE_TYPE            ((vltINT16) ( dbErrOffset + 21 ))
#define ccsERR_DB_INV_RECEL          ((vltINT16) ( dbErrOffset + 22 ))
#define ccsERR_DB_ATTR_TYPE          ((vltINT16) ( dbErrOffset + 23 ))
#define ccsERR_DB_INV_POINT          ((vltINT16) ( dbErrOffset + 24 ))
#define ccsERR_DB_INV_ATTR           ((vltINT16) ( dbErrOffset + 25 ))
#define ccsERR_DB_INV_ALIAS          ((vltINT16) ( dbErrOffset + 26 ))
#define ccsERR_DB_QUALITY            ((vltINT16) ( dbErrOffset + 27 ))
#define ccsERR_DB_INV_ADDR           ((vltINT16) ( dbErrOffset + 28 ))
#define ccsERR_DB_LIST               ((vltINT16) ( dbErrOffset + 29 ))
#define ccsERR_DB_CONFIG             ((vltINT16) ( dbErrOffset + 30 ))
#define ccsERR_DB_INV_RESID          ((vltINT16) ( dbErrOffset + 31 ))
#define ccsERR_DB_MAX_LISTS          ((vltINT16) ( dbErrOffset + 32 ))
#define ccsERR_DB_ENV_NAME           ((vltINT16) ( dbErrOffset + 33 ))
#define ccsERR_DB_ADDR               ((vltINT16) ( dbErrOffset + 34 ))
#define ccsERR_DB_WRMODE             ((vltINT16) ( dbErrOffset + 35 ))
#define ccsERR_DB_LISTID             ((vltINT16) ( dbErrOffset + 36 ))
#define ccsERR_DB_LIST_FLAG          ((vltINT16) ( dbErrOffset + 37 ))
#define ccsERR_DB_BLOCK_CNT          ((vltINT16) ( dbErrOffset + 38 ))
#define ccsERR_DB_NOCLASS            ((vltINT16) ( dbErrOffset + 39 ))
#define ccsERR_DB_PARSEATTR          ((vltINT16) ( dbErrOffset + 40 ))
#define ccsERR_DB_CONVERT            ((vltINT16) ( dbErrOffset + 41 ))
#define ccsERR_DB_INV_FIELD          ((vltINT16) ( dbErrOffset + 42 ))
#define ccsERR_DB_SSMA               ((vltINT16) ( dbErrOffset + 50 ))
#define ccsERR_DB_NO_RTAP            ((vltINT16) ( dbErrOffset + 51 ))
#define ccsERR_DB_REOPEN             ((vltINT16) ( dbErrOffset + 52 ))
#define ccsERR_DB_MAXLINK            ((vltINT16) ( dbErrOffset + 53 ))
#define ccsERR_DB_RESTORE            ((vltINT16) ( dbErrOffset + 54 ))
#define ccsERR_DB_RESTORE_SYNTAX     ((vltINT16) ( dbErrOffset + 56 ))
#define ccsERR_DB_RESTORE_WHAT       ((vltINT16) ( dbErrOffset + 57 ))
#define ccsERR_DB_SERVER             ((vltINT16) ( dbErrOffset + 58 ))
#define ccsERR_DB_CE                 ((vltINT16) ( dbErrOffset + 59 ))
#define ccsERR_DB_RANGE              ((vltINT16) ( dbErrOffset + 60 ))
#define ccsERR_DB_ENV_TOO_LONG       ((vltINT16) ( dbErrOffset + 61 ))
#define ccsERR_DB_NOT_SUPPORTED      ((vltINT16) ( dbErrOffset + 99 ))

#else

#define ccsERR_DB_OPEN               (static_cast<vltINT16> ( dbErrOffset + 1 ))
#define ccsERR_DB_CLOSE              (static_cast<vltINT16> ( dbErrOffset + 2 ))
#define ccsERR_DB_GET_HANDLE         (static_cast<vltINT16> ( dbErrOffset + 3 ))
#define ccsERR_DB_INV_LINK           (static_cast<vltINT16> ( dbErrOffset + 4 ))
#define ccsERR_DB_INV_ACTION         (static_cast<vltINT16> ( dbErrOffset + 5 ))
#define ccsERR_DB_QUERY              (static_cast<vltINT16> ( dbErrOffset + 6 ))
#define ccsERR_DB_GETCWP             (static_cast<vltINT16> ( dbErrOffset + 7 ))
#define ccsERR_DB_SETCWP             (static_cast<vltINT16> ( dbErrOffset + 8 ))
#define ccsERR_DB_GROUP              (static_cast<vltINT16> ( dbErrOffset + 9 ))
#define ccsERR_DB_CATEGORY           (static_cast<vltINT16> ( dbErrOffset + 10 ))
#define ccsERR_DB_WRITE              (static_cast<vltINT16> ( dbErrOffset + 11 ))
#define ccsERR_DB_READ               (static_cast<vltINT16> ( dbErrOffset + 12 ))
#define ccsERR_DB_LCU                (static_cast<vltINT16> ( dbErrOffset + 13 ))
#define ccsERR_DB_LCU_FORMAT         (static_cast<vltINT16> ( dbErrOffset + 14 ))
#define ccsERR_DB_LOCK               (static_cast<vltINT16> ( dbErrOffset + 15 ))
#define ccsERR_DB_UNLOCK             (static_cast<vltINT16> ( dbErrOffset + 16 ))
#define ccsERR_DB_LCU_REPLY          (static_cast<vltINT16> ( dbErrOffset + 17 ))
#define ccsERR_DB_INV_NAME           (static_cast<vltINT16> ( dbErrOffset + 20 ))
#define ccsERR_DB_DE_TYPE            (static_cast<vltINT16> ( dbErrOffset + 21 ))
#define ccsERR_DB_INV_RECEL          (static_cast<vltINT16> ( dbErrOffset + 22 ))
#define ccsERR_DB_ATTR_TYPE          (static_cast<vltINT16> ( dbErrOffset + 23 ))
#define ccsERR_DB_INV_POINT          (static_cast<vltINT16> ( dbErrOffset + 24 ))
#define ccsERR_DB_INV_ATTR           (static_cast<vltINT16> ( dbErrOffset + 25 ))
#define ccsERR_DB_INV_ALIAS          (static_cast<vltINT16> ( dbErrOffset + 26 ))
#define ccsERR_DB_QUALITY            (static_cast<vltINT16> ( dbErrOffset + 27 ))
#define ccsERR_DB_INV_ADDR           (static_cast<vltINT16> ( dbErrOffset + 28 ))
#define ccsERR_DB_LIST               (static_cast<vltINT16> ( dbErrOffset + 29 ))
#define ccsERR_DB_CONFIG             (static_cast<vltINT16> ( dbErrOffset + 30 ))
#define ccsERR_DB_INV_RESID          (static_cast<vltINT16> ( dbErrOffset + 31 ))
#define ccsERR_DB_MAX_LISTS          (static_cast<vltINT16> ( dbErrOffset + 32 ))
#define ccsERR_DB_ENV_NAME           (static_cast<vltINT16> ( dbErrOffset + 33 ))
#define ccsERR_DB_ADDR               (static_cast<vltINT16> ( dbErrOffset + 34 ))
#define ccsERR_DB_WRMODE             (static_cast<vltINT16> ( dbErrOffset + 35 ))
#define ccsERR_DB_LISTID             (static_cast<vltINT16> ( dbErrOffset + 36 ))
#define ccsERR_DB_LIST_FLAG          (static_cast<vltINT16> ( dbErrOffset + 37 ))
#define ccsERR_DB_BLOCK_CNT          (static_cast<vltINT16> ( dbErrOffset + 38 ))
#define ccsERR_DB_NOCLASS            (static_cast<vltINT16> ( dbErrOffset + 39 ))
#define ccsERR_DB_PARSEATTR          (static_cast<vltINT16> ( dbErrOffset + 40 ))
#define ccsERR_DB_CONVERT            (static_cast<vltINT16> ( dbErrOffset + 41 ))
#define ccsERR_DB_INV_FIELD          (static_cast<vltINT16> ( dbErrOffset + 42 ))
#define ccsERR_DB_SSMA               (static_cast<vltINT16> ( dbErrOffset + 50 ))
#define ccsERR_DB_NO_RTAP            (static_cast<vltINT16> ( dbErrOffset + 51 ))
#define ccsERR_DB_REOPEN             (static_cast<vltINT16> ( dbErrOffset + 52 ))
#define ccsERR_DB_MAXLINK            (static_cast<vltINT16> ( dbErrOffset + 53 ))
#define ccsERR_DB_RESTORE            (static_cast<vltINT16> ( dbErrOffset + 54 ))
#define ccsERR_DB_RESTORE_SYNTAX     (static_cast<vltINT16> ( dbErrOffset + 56 ))
#define ccsERR_DB_RESTORE_WHAT       (static_cast<vltINT16> ( dbErrOffset + 57 ))
#define ccsERR_DB_SERVER             (static_cast<vltINT16> ( dbErrOffset + 58 ))
#define ccsERR_DB_CE                 (static_cast<vltINT16> ( dbErrOffset + 59 ))
#define ccsERR_DB_RANGE              (static_cast<vltINT16> ( dbErrOffset + 60 ))
#define ccsERR_DB_ENV_TOO_LONG       (static_cast<vltINT16> ( dbErrOffset + 61 ))
#define ccsERR_DB_NOT_SUPPORTED      (static_cast<vltINT16> ( dbErrOffset + 99 ))

#endif

#endif


