/***********************************************************
# "@(#) $Id$" 
#
# Error Include File    Created on  Jul 28 08:06:58 2015
# 
# This file has been generated by a utility
# 
#  !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
# 
***********************************************************/
#ifndef timsERRORS_H
#define timsERRORS_H 

#ifndef CCS_H
#include "ccs.h"
#endif 

#define timsErrOffset 300
 
#ifndef __cplusplus

#define ccsERR_TIMS_FAILED           ((vltINT16) ( timsErrOffset + 1 ))
#define ccsERR_TIMER_REJECTED        ((vltINT16) ( timsErrOffset + 2 ))
#define ccsERR_TIMER_SCHEDULE        ((vltINT16) ( timsErrOffset + 3 ))
#define ccsERR_TIMER_STARTTIME       ((vltINT16) ( timsErrOffset + 4 ))
#define ccsERR_TIMS_DB_POINT         ((vltINT16) ( timsErrOffset + 5 ))
#define ccsERR_TIMS_NOSIMULATION     ((vltINT16) ( timsErrOffset + 6 ))
#define ccsERR_TIMS_CONVERT          ((vltINT16) ( timsErrOffset + 7 ))
#define ccsERR_TIMER_INVALID_ID      ((vltINT16) ( timsErrOffset + 8 ))
#define ccsERR_TIMER_REPORT          ((vltINT16) ( timsErrOffset + 9 ))
#define ccsERR_TIMS_PARAM            ((vltINT16) ( timsErrOffset + 10 ))

#else

#define ccsERR_TIMS_FAILED           (static_cast<vltINT16> ( timsErrOffset + 1 ))
#define ccsERR_TIMER_REJECTED        (static_cast<vltINT16> ( timsErrOffset + 2 ))
#define ccsERR_TIMER_SCHEDULE        (static_cast<vltINT16> ( timsErrOffset + 3 ))
#define ccsERR_TIMER_STARTTIME       (static_cast<vltINT16> ( timsErrOffset + 4 ))
#define ccsERR_TIMS_DB_POINT         (static_cast<vltINT16> ( timsErrOffset + 5 ))
#define ccsERR_TIMS_NOSIMULATION     (static_cast<vltINT16> ( timsErrOffset + 6 ))
#define ccsERR_TIMS_CONVERT          (static_cast<vltINT16> ( timsErrOffset + 7 ))
#define ccsERR_TIMER_INVALID_ID      (static_cast<vltINT16> ( timsErrOffset + 8 ))
#define ccsERR_TIMER_REPORT          (static_cast<vltINT16> ( timsErrOffset + 9 ))
#define ccsERR_TIMS_PARAM            (static_cast<vltINT16> ( timsErrOffset + 10 ))

#endif

#endif


